name: Build and Push Docker Image

on:
  push:
    branches: [ "master", "cicd-test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.0

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: jh981113/sajuoct:latest

      # 5. Optional: Log out from Docker Hub (보안 차원에서 로그아웃)
      - name: Log out from Docker Hub
        run: docker logout

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.10.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Pull the Docker image from Docker Hub
            docker pull jh981113/sajuoct:latest
          
            # Stop and remove the existing container if it's running
            docker stop java-app || true
            docker rm java-app || true
          
            # Run the new Docker container
            docker run -d --name java-app -p 80:8080 jh981113/sajuoct:latest
          
            # Check the container status
            docker ps -a
          EOF